"""true_anon

Revision ID: 53ba98f9b4d4
Revises: c4f98ebffcfe
Create Date: 2025-06-17 17:54:09.878061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ba98f9b4d4'
down_revision: Union[str, None] = 'c4f98ebffcfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['user_id'])
    # ### end Alembic commands ###
