"""tgread_table

Revision ID: d9cbe7abb8fb
Revises: d39686b1fcaa
Create Date: 2024-09-19 20:25:42.663760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9cbe7abb8fb'
down_revision: Union[str, None] = 'd39686b1fcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_id'), 'threads', ['id'], unique=False)
    op.create_index(op.f('ix_threads_thread_id'), 'threads', ['thread_id'], unique=True)
    op.drop_index('ix_UserMessage_id', table_name='UserMessage', if_exists=True)
    op.drop_index('ix_UserMessage_message_id', table_name='UserMessage', if_exists=True)
    op.drop_table('UserMessage', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserMessage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], name='UserMessage_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='UserMessage_pkey')
    )
    op.create_index('ix_UserMessage_message_id', 'UserMessage', ['message_id'], unique=True)
    op.create_index('ix_UserMessage_id', 'UserMessage', ['id'], unique=False)
    op.drop_index(op.f('ix_threads_thread_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
